CreateExam/Models/CreateExamVM.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace CreateExam.Models
{
	public class CreateExamVM
	{
		public List<SelectListItem> TitleValues { get; set; }
		public string Text { get; set; }
		public string Title { get; set; }
		public string TitleUrl { get; set; }
		public List<string> Questions { get; set; }
		public List<string> Answers { get; set; }
		public List<string> CorrectAnswers { get; set; }

	}
}

CreateExam/Models/UserVM.cs
namespace CreateExam.Models
{
	public class UserVM
	{
		public string UserName { get; set; }
		public string Password { get; set; }
	}
}

CreateExam/Controllers/CreateExamController.cs
using CreateExam.Data.Context;
using CreateExam.Data.Entities;
using CreateExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Net;

namespace CreateExam.Controllers
{
	[Authorize]
	public class CreateExamController : Controller
	{
		public IActionResult Index()
		{
			try
			{
				CreateExamVM model = new CreateExamVM();
				model.TitleValues = GetTitleFromWired();
				return View(model);
			}
			catch (Exception e)
			{
				TempData["ErrorMessage"] = e.Message;
				return RedirectToAction("Error", "Home");
			}
		}

		[HttpPost]
		public IActionResult Index(CreateExamVM model)
		{
			Exam exam = new Exam();
			exam.CreateDate = DateTime.Now;
			exam.Title = model.Title;
			exam.Text = model.Text;
			exam.Questions = new List<Question>();

			for (int i = 0; i < 4; i++)
			{
				List<string> answers = new List<string>();
				for (int j = i * 4; j < (i * 4 + 4); j++)
				{
					answers.Add(model.Answers[j]);
				}

				exam.Questions.Add(new Question()
				{
					QuestionText = model.Questions[i],
					CorrectAnswer = model.CorrectAnswers[i],
					AnswerA = answers[0],
					AnswerB = answers[1],
					AnswerC = answers[2],
					AnswerD = answers[3],
				});
			}

			using (Context context = new Context())
			{
				context.Exams.Add(exam);
				context.SaveChanges();
			}

			return RedirectToAction("Index", "Home");
		}

		public List<SelectListItem> GetTitleFromWired()
		{
			WebRequest request = HttpWebRequest.Create("https://www.wired.com/");
			WebResponse response = request.GetResponse();
			StreamReader reader = new StreamReader(response.GetResponseStream());

			string html = reader.ReadToEnd();
			int startIndex = html.IndexOf("summary-item__content summary-item__content--no-rubric\">");
			int length = html.Substring(startIndex).IndexOf("</section>");
			html = html.Substring(startIndex, length);

			List<SelectListItem> result = new List<SelectListItem>();

			for (int i = 0; i < 5; i++)
			{
				//get the a element from html
				int start = html.IndexOf("<a");
				int linkLength = html.IndexOf("</a>");
				string linkHtml = html.Substring(start, linkLength);

				//get the a href from html
				int linkStartIndex = linkHtml.IndexOf("\"/") + 1;
				int linkEnd = linkHtml.IndexOf(" ", linkStartIndex);
				string href = "https://www.wired.com" + linkHtml.Substring(linkStartIndex, linkEnd - linkStartIndex - 1);

				//get the a title from html
				int titleStartIndex = linkHtml.IndexOf("data-recirc-pattern=\"summary-item\"") + 35;
				int titleLength = linkHtml.IndexOf("</h2>");
				string title = linkHtml.Substring(titleStartIndex, titleLength - titleStartIndex);

				//remove added link from html
				html = html.Substring(start + linkLength);
				result.Add(new SelectListItem()
				{
					Text = title,
					Value = href
				});
			}
			return result;
		}

		public JsonResult GetTextFromWired(string url)
		{
			try
			{
				WebRequest request = HttpWebRequest.Create(url);
				WebResponse response = request.GetResponse(); //sometimes wired server returns 402 Payment Required error. Please Re-open sln to fix it.
				StreamReader reader = new StreamReader(response.GetResponseStream());

				string html = reader.ReadToEnd();
				int startIndex = html.IndexOf("<div class=\"body__inner-container\">");

				if (startIndex == -1)
					startIndex = html.IndexOf("<div><p>");

				int length = html.Substring(startIndex).IndexOf("</p>");
				html = html.Substring(startIndex, length);
				return Json(html);
			}
			catch (Exception e)
			{
				string[] error = new string[2];
				error[0] = "error";
				error[1] = e.Message;
				return Json(error);
			}
		}
	}
}

CreateExam/Controllers/HomeController.cs
using CreateExam.Data.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CreateExam.Controllers
{
	[Authorize]
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			using (Context context = new Context())
			{
				var data = context.Exams.OrderByDescending(x => x.CreateDate).ToList();
				return View(data);
			}
		}

		public IActionResult DeleteExam(int id)
		{
			using (Context context = new Context())
			{
				var examValue = context.Exams.FirstOrDefault(x => x.ExamID == id);
				context.Exams.Remove(examValue);
				context.SaveChanges();
				return RedirectToAction("Index");
			}
		}

		public IActionResult Error()
		{
			return View();
		}
	}
}

CreateExam/Controllers/LoginController.cs
using CreateExam.Data.Context;
using CreateExam.Data.Entities;
using CreateExam.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authentication;

namespace CreateExam.Controllers
{
	[AllowAnonymous]
	public class LoginController : Controller
	{
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(UserVM user)
		{
			using (Context db = new Context())
			{
				User loggingUser = db.Users.FirstOrDefault(x => x.UserName == user.UserName && x.Password == user.Password);

				if (loggingUser != null)
				{
					var claims = new List<Claim>()
					{
						new Claim(ClaimTypes.Name, loggingUser.UserName)
					};

					var useridentity = new ClaimsIdentity(claims, "user");
					ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
					await HttpContext.SignInAsync(principal);

					return RedirectToAction("Index", "Home");
				}
			}

			ViewBag.Message = "Kullanıcı adı veya şifre hatalı!";
			return View();
		}

		[Authorize]
		public async Task<IActionResult> Logout()
		{
			await HttpContext.SignOutAsync();
			return RedirectToAction("Index", "Login");
		}

	}
}

CreateExam/Controllers/TakeExamController.cs
using CreateExam.Data.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;

namespace CreateExam.Controllers
{
	[Authorize]
	public class TakeExamController : Controller
	{
		public IActionResult Index(int id)
		{
			using (Context context = new Context())
			{
				var examValue = context.Exams.Include(x => x.Questions).FirstOrDefault(y => y.ExamID == id);

				if (examValue == null)
					return NotFound();

				return View(examValue);
			}
		}

		[HttpPost]
		public JsonResult GetResult(string[] answers)
		{
			using (Context context = new Context())
			{
				var examValue = context.Exams.Include(x => x.Questions).FirstOrDefault(x => x.ExamID == Convert.ToInt32(answers[0]));
				List<string> correctAnswers = new List<string>();
				
				foreach (var item in examValue.Questions)
				{
					correctAnswers.Add(item.CorrectAnswer);
				}
				return Json(correctAnswers);
			}
		}
	}
}

CreateExam/Views/CreateExam/Index.cshtml
@model CreateExamVM
@{
    ViewData["Title"] = "Sınav Oluştur";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1 class="display-4 text-center">Sınav Oluştur</h1>
<br />
@using (Html.BeginForm("Index", "CreateExam", FormMethod.Post))
{
    <!--Removed for Html.Raw()-->
    @*@Html.DropDownListFor(x => x.SelectedTitle, Model.TitleValues, new { @class = "form-control", placeholder = "Yazı", id = "selectTitle" })*@

    <div class="jumbotron">
        <select class="form-control" id="selectTitle" name="TitleUrl" required>
            <option value="">Bir yazı seçiniz..</option>
            @foreach (var item in Model.TitleValues)
            {
                <option value="@item.Value">@Html.Raw(item.Text)</option>
            }
        </select>
        <div style="display:none;" id="divfortext"></div>

        @Html.HiddenFor(x => x.Title, new { @id = "hiddenTitle" })
        <br />
        @Html.TextAreaFor(x => x.Text, 10, 3, new { @class = "form-control", placeholder = "Metin İçeriği", id = "txtText", required = "required" })
        <br />
    </div>
    @for (int i = 1; i <= 4; i++)
    {
        <div class="jumbotron">
            <h4 class="text-center mb-3">Soru @i</h4>
            <input type="text" class="form-control mb-3" name="Questions" required placeholder="Soru @i" />
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control mb-1" name="Answers" required placeholder="A)" />
                </div>
                <div class="col">

                    <input type="text" class="form-control mb-1" name="Answers" required placeholder="B)" />
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control mb-1" name="Answers" required placeholder="C)" />
                </div>
                <div class="col">

                    <input type="text" class="form-control mb-1" name="Answers" required placeholder="D)" />
                </div>
            </div>
            <select class="form-control mt-1" name="CorrectAnswers" required>
                <option value="">Doğru Cevap Seç</option>
                <option value="A">A</option>
                <option value="B">B</option>
                <option value="C">C</option>
                <option value="D">D</option>
            </select>
        </div>
        <hr class="mt-5" />
    }

    <br />
    <button type="submit" class="btn btn-primary submit mb-4 form-control">Sınav Oluştur</button>
}
<script src="~/lib/jquery/jquery.min.js"></script>

<script>
    $('#selectTitle').on('change', function () {
        var textUrl = $(this).val();
        var textTitle = $(this).find('option:selected').text();
        if (textUrl != "") {
            $.ajax({
                type: 'Get',
                url: '/CreateExam/GetTextFromWired/',
                data: { "url": textUrl },
                dataType: 'json',
                success: function (data) {

                    if (data[0] != "error") {
                        //$('#txtText').val(data); html is displaying :(
                        $('#divfortext').html(data);
                        $('#txtText').val($('#divfortext').text());

                        //set the title to hidden input
                        $('#hiddenTitle').val(textTitle);
                    }
                    else {
                        $("#selectTitle option").prop("selected", false);
                        alert(data[1]);
                    }
                }
            });
        }
        else {
            $('#txtText').val("");
        }
    });
</script>

CreateExam/Views/Home/Index.cshtml
@model List<Exam>
@{
    ViewData["Title"] = "Sınav Listesi";
}

<div class="text-center">
    <h1 class="display-4">Sınav Listesi</h1>
    <br />
    <table class="table table-bordered">
        <tr>
            <th>#</th>
            <th>Başlık</th>
            <th>Tarih</th>
            <th></th>
        </tr>
        <tbody>
            @foreach (var exam in Model)
            {
                <tr>
                    <td>@exam.ExamID</td>
                    <td><a href="@Url.Action("Index","TakeExam",new {@id=exam.ExamID })">@Html.Raw(exam.Title)</a></td>
                    <td>@exam.CreateDate.ToString("yyyy-MM-dd")</td>
                    <td><a class="btn btn-danger text-white" href="/Home/DeleteExam/@exam.ExamID">Sil</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

CreateExam/Views/Login/Index.cshtml
@model UserVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        .btn-color {
            background-color: #0e1c36;
            color: #fff;
        }

        .profile-image-pic {
            height: 200px;
            width: 200px;
            object-fit: cover;
        }

        .cardbody-color {
            background-color: #ebf2fa;
        }

        a {
            text-decoration: none;
        }
    </style>
    <title>Giriş Yap - CreateExam</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="text-center text-dark mt-5">Kullanıcı Girişi</h2>
                <div class="text-center mb-5 text-dark"> --- CreateExam ---</div>
                <div class="card my-5">
                    @using (Html.BeginForm("Index", "Login", FormMethod.Post, new { @class = "card-body cardbody-color p-lg-5" }))
                    {
                        <div class="text-center">
                            <img src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295397__340.png" class="img-fluid profile-image-pic img-thumbnail rounded-circle my-3" alt="profile" style="width:200px;">
                        </div>

                        <div class="mb-3">
                            @Html.TextBoxFor(x=>x.UserName, new {@class="form-control", placeholder= "Kullanıcı Adı" })
                        </div>
                        <div class="mb-3">
                            @Html.TextBoxFor(x => x.Password, new { @class = "form-control", placeholder = "Şifre", type="password" })
                        </div>

                        @if (ViewBag.Message != null)
                        {
                            <div class="text-center text-danger mb-2"><strong>@ViewBag.Message</strong></div>
                        }
                        <div class="text-center"><button type="submit" class="btn btn-color px-5 mb-5 w-100">Giriş Yap</button></div>
                        <div id="emailHelp" class="form-text text-center mb-5 text-dark">
                            @DateTime.Now.Year &copy;  <a href="https://www.linkedin.com/in/trkaydn/">Tarık Aydın</a> Tüm Hakları Saklıdır.
                        </div>
                    }
                </div>

            </div>
        </div>
    </div>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

CreateExam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CreateExam</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CreateExam</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Sınav Listesi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreateExam" asp-action="Index">Sınav Oluştur</a>
                        </li>

                    </ul>
                    <a href="@Url.Action("Logout","Login")" class="btn btn-danger">Çıkış Yap</a>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            @DateTime.Now.Year &copy;  <a href="https://www.linkedin.com/in/trkaydn/">Tarık Aydın</a> Tüm Hakları Saklıdır.
        </div>
    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</body>
</html>

CreateExam/Views/TakeExam/Index.cshtml
@model Exam
@{
    ViewData["Title"] = "Sınav Çöz";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int i = 1;
}

<div class="card">
    <div class="text-center">
        <h1 class="display-4">@Model.Title</h1>
    </div>
    <p style="padding:10px">@Model.Text</p>
</div>
<br />
<input type="hidden" id="ExamID" value="@Model.ExamID" />
<div class="row">
    @foreach (var question in Model.Questions)
    {
        <div class="col-6 mt-3 mb-3" id="questiondiv-@i">
            <h5>@i) @question.QuestionText</h5>

            <label id="label-@i-A"><input type="radio" name="answer-@question.QuestionID" value="A"> A) @question.AnswerA</label>
            <br />
            <label id="label-@i-B"><input type="radio" name="answer-@question.QuestionID" value="B"> B) @question.AnswerB</label>
            <br />
            <label id="label-@i-C"><input type="radio" name="answer-@question.QuestionID" value="C"> C) @question.AnswerC</label>
            <br />
            <label id="label-@i-D"><input type="radio" name="answer-@question.QuestionID" value="D"> D) @question.AnswerD</label>

        </div>

        i++;
    }

    <div id="divforresult" class="mb-3"></div>
    <button class="btn btn-success btn-block" id="finishExam">Sınavı Tamamla</button>
    <button class="btn btn-warning btn-block mt-2" id="refreshBtn">Tekrar Çöz</button>
</div>

<script src="~/lib/jquery/jquery.min.js"></script>
<script>
    $('#finishExam').on('click', function () {

        //create array for ajax
        var stringArray = new Array();
        stringArray[0] = $("#ExamID").val();
        stringArray[1] = $("#questiondiv-1 input[type='radio']:checked").val();
        stringArray[2] = $("#questiondiv-2 input[type='radio']:checked").val();
        stringArray[3] = $("#questiondiv-3 input[type='radio']:checked").val();
        stringArray[4] = $("#questiondiv-4 input[type='radio']:checked").val();

        $.ajax({
            type: 'post',
            url: '/TakeExam/GetResult/',
            data: { 'answers': stringArray },
            dataType: 'json',
            success: function (data) {
                var i = 1, trueCount = 0, falseCount = 0, emptyCount = 0;
                $.each(data, function (index, value) {

                    if (stringArray[i] == value) {
                        $("#questiondiv-" + i + " > #label-" + i + "-" + value).css("background-color", "GreenYellow"); //true answer green css
                        trueCount++;
                    }
                    else if (typeof(stringArray[i]) == "undefined") {
                        $("#questiondiv-" + i + " > #label-" + i + "-" + value).css("background-color", "DarkOrange"); // empty answer orange css
                        emptyCount++;
                    }
                    else {
                        $("#questiondiv-" + i + " > #label-" + i + "-" + value).css("background-color", "GreenYellow");  //true answer green css
                        $("#questiondiv-" + i + " > #label-" + i + "-" + stringArray[i]).css("background-color", "#dc3545"); //selected false answer red css
                        falseCount++;
                    }
                    i++;
                });

                $('#divforresult').html("<br>Doğru Cevap Sayısı: " + trueCount + "<br>Yanlış Cevap Sayısı: " + falseCount + "<br>Boş Cevap Sayısı: " + emptyCount);
            }
        });
        $(this).attr('disabled', 'disabled');
    });

    $('#refreshBtn').on('click', function () {
        window.location.reload();
    });
</script>